HELBImmo/HELBImmo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('criteria/', user_views.criteria, name='criteria'),
    path('notifications/', user_views.NotficationsView.as_view(), name='notifications'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('ajax/read/', user_views.notif_read, name='read-notification'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HELBImmo/blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostDetailView, 
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostStatsView,
    UserPostListView,
    FavoritesListView,
    SearchResultsListView
    )
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('search/', SearchResultsListView.as_view(), name='search-results'),
    path('favorites/', FavoritesListView.as_view(), name='user-favorites'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/stats/', PostStatsView.as_view(), name='post-stats'),
    path('about/', views.about, name='blog-about'),
    path('ajax/fav/', views.add_favorite, name='favorite'),
    path('ajax/consult/', views.post_consulted, name='post-consult'),
    path('ajax/question/new', views.post_question, name='question-new'),
    path('ajax/question/delete/<int:pk>', views.delete_question, name='question-delete'),
    path('ajax/question/answer', views.post_answer, name='answer-question'),
    path('ajax/question/answer/delete/<int:pk>', views.delete_answer, name='answer-delete')
]

HELBImmo/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse

#Post model, type_bien is used to differenciate between types of real estate
class Post(models.Model):
    type_bien = models.CharField(max_length=20, default='Maison')
    title = models.CharField( max_length=100 )
    content = models.TextField()
    date_posted = models.DateTimeField( default=timezone.now )
    author = models.ForeignKey( User, on_delete=models.CASCADE )
    price = models.DecimalField(max_digits=16, decimal_places=2, default=0)
    livable_surface = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    room_amount = models.IntegerField(default=0)
    nb_etage = models.IntegerField(default=1)
    situe_etage = models.IntegerField(default=0)
    thumbnail = models.ImageField(default='no_photo.jpg', upload_to='gallery_images')
    to_sell = models.BooleanField(default=True)
    #addresse
    longitude = models.DecimalField(max_digits=13, decimal_places=10)
    latitude = models.DecimalField(max_digits=12, decimal_places=10)
    road_num = models.CharField( max_length=100)
    region_city = models.CharField(max_length=100)
    country_code = models.CharField(max_length=2)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    def save(self, **kwargs):
        super().save(**kwargs)

        img = Image.open(self.thumbnail.path)
        
        if img.height > 1080 or img.width > 1920:
            output_size = (1920, 1080)
            img.thumbnail(output_size)

        img.save(self.thumbnail.path)

#single consultation of a given post, created after loading it's detailed page
class PostConsult(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateField( default=timezone.now)

    def __str__(self):
        return self.post.title + " consult"

#favorite of a post, used for the watchlist
class PostFavorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField( default=timezone.now)

    def __str__(self):
        return self.user.__str__() + " favorite on " + self.post.title

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return self.user.__str__() + ' on ' + self.post.__str__() + ' : ' + self.content

#answer is a different model due to it linking to the question rather than the post itself
class Reponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.OneToOneField(Question, on_delete=models.CASCADE, blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return 'answer to ' + self.question.__str__()

HELBImmo/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView, 
    DetailView, 
    CreateView,
    UpdateView,
    DeleteView
    )
from django.http import JsonResponse, request
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils import timezone
from users.models import Notification, Criteria
from .models import Post, PostConsult, PostFavorite, Question, Reponse
from .forms import PostCreateForm
import datetime

#used because of amount per page customization, use paginate function on context to get correct pagination
class PaginatedMixin():
    def paginate(self, context):
        data = self.get_queryset()
        paginate_by = self.request.GET.get('paginate_by', 5)
        page = self.request.GET.get('page', 1)

        paginator = Paginator(data, paginate_by)

        try:
            page_obj = paginator.get_page(page)
        except PageNotAnInteger:
            page_obj = paginator.get_page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        context['per_page_values'] = [5, 10, 25, 50]
        context['paginator'] = paginator
        context['page_obj'] = page_obj
        context[self.context_object_name] = page_obj

#used to get favorites of current user
class FavoritesMixin():
    def get_user_favorites(self):
        if self.request.user.is_authenticated:
            favs = PostFavorite.objects.filter(user=self.request.user)
            return Post.objects.filter(id__in=favs.values('post'))
        else:
            return None

#while it is called add_favorite, it is also used to remove them
def add_favorite(request):
    if request.user.is_authenticated:
        user = request.user
        post = Post.objects.filter(pk=request.GET.get('postid', None)).first()
        data = {
            'added': True
        }

        fav = PostFavorite.objects.filter(user=user, post=post)

        if fav:
            data['added'] = False
            fav.delete()
        else:
            fav = PostFavorite(user=user, post=post)
            fav.save()
        
        return JsonResponse(data)
    return JsonResponse({'added': 'no'})

def post_consulted(request):
    view = PostConsult(post=Post.objects.filter(pk=request.GET.get('postid', None)).first())

    view.save()
    
    data = { 'good': view.__str__() }

    return JsonResponse(data)

def post_question(request):
    content = request.POST.get('question')

    if request.user.is_authenticated and content != None and content != '':
        post = Post.objects.filter(id=request.POST.get('postid')).first()
        question = Question(user=request.user, post=post, content=content)
        question.save()
        return render(request, 'blog/subtemplates/question.html', {'question': question})

def delete_question(request, **kwargs):
    question = Question.objects.filter(id=kwargs.get('pk')).first()

    if request.user.is_authenticated and request.user == question.user:
        question.delete()

def post_answer(request):
    content = request.POST.get('content')

    if request.user.is_authenticated and content != None and content != '':
        question = Question.objects.filter(id=request.POST.get('questionid')).first()
        reponse = Reponse(user=request.user, question=question, content=content)
        reponse.save()
        return render(request, 'blog/subtemplates/reponse.html', {'reponse': reponse})

def delete_answer(request, **kwargs):
    reponse = Reponse.objects.filter(id=kwargs.get('pk')).first()

    if request.user.is_authenticated and request.user == reponse.user:
        question = reponse.question
        reponse.delete()

        return render(request, 'blog/subtemplates/reponse_form.html', {'question': question})

#home page
class PostListView(PaginatedMixin, FavoritesMixin, ListView):
    model = Post
    template_name = 'blog/home.html' # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.paginate(context)
        context['user_favs'] = self.get_user_favorites()
        if self.request.user.is_authenticated:
            context['notif_count'] = Notification.objects.filter(user=self.request.user, read=False).count()
        return context

#serach results
class SearchResultsListView(PaginatedMixin, FavoritesMixin, ListView):
    model = Post
    template_name = 'blog/search_results.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        terms = self.request.GET.get('q')
        results = Post.objects.filter(
            Q(content__icontains=terms) | Q(title__icontains=terms) | Q(region_city__icontains=terms)
        ).order_by('-date_posted')

        if ( self.request.GET.get('budgetMax') ):
            results = results.filter(price__lte=self.request.GET.get('budgetMax'))
        if ( self.request.GET.get('budgetMin') ):
            results = results.filter(price__gte=self.request.GET.get('budgetMin'))

        return results

    def get_context_data(self, **kwargs):
        context = super(SearchResultsListView, self).get_context_data(**kwargs)

        self.paginate(context)

        context['user_favs'] = self.get_user_favorites()

        if self.request.user.is_authenticated:
            context['notif_count'] = Notification.objects.filter(user=self.request.user, read=False).count()

        context['terms'] = self.request.GET.get('q')
        context['title'] = 'Recherche - ' + self.request.GET.get('q')
        return context

#posts of a given user
class UserPostListView(PaginatedMixin, FavoritesMixin, ListView):
    model = Post
    template_name = 'blog/user_posts.html' # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

    def get_context_data(self, **kwargs):
        context = super(UserPostListView, self).get_context_data(**kwargs)

        self.paginate(context)

        context['user_favs'] = self.get_user_favorites()

        if self.request.user.is_authenticated:
            context['notif_count'] = Notification.objects.filter(user=self.request.user, read=False).count()

        context['author'] = User.objects.filter(username=self.kwargs.get('username')).first()
        context['title'] = self.kwargs.get('username')
        return context

#watchlist
class FavoritesListView(PaginatedMixin, FavoritesMixin, ListView):
    model = Post
    template_name = 'blog/favorites.html' # <app>/<model>_<viewtype>.html
    context_object_name = 'favs'
    paginate_by = 5

    def get_queryset(self):
        return PostFavorite.objects.filter(user=self.request.user).order_by('-date')

    def get_context_data(self, **kwargs):
        context = super(FavoritesListView, self).get_context_data(**kwargs)

        self.paginate(context)
        
        context['user_favs'] = self.get_user_favorites()

        if self.request.user.is_authenticated:
            context['notif_count'] = Notification.objects.filter(user=self.request.user, read=False).count()

        context['title'] = 'Votre Watchlist'

        return context

#detailed view of a post
class PostDetailView(FavoritesMixin, DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        
        context['user_favs'] = self.get_user_favorites()
        context['title'] = Post.objects.filter(id=self.kwargs.get('pk')).first().title
        context['questions'] = Question.objects.filter(post=self.kwargs.get('pk')).order_by('-date_posted')

        if self.request.user.is_authenticated:
            context['notif_count'] = Notification.objects.filter(user=self.request.user, read=False).count()

        return context

#statistics of a given post only accessible to author
class PostStatsView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Post
    template_name = 'blog/post_stats.html'
    context_object_name = 'post'

    #Warning : gives runtime errors due to the use of basic datetimes, needs to be converted to timezone info
    def get_context_data(self, **kwargs):
        context = super(PostStatsView, self).get_context_data(**kwargs)

        dateTimeStat = datetime.datetime.combine(timezone.now(), datetime.time.max) - datetime.timedelta(29)
        dateStat = dateTimeStat.date()

        post = Post.objects.filter(pk=self.kwargs.get('pk')).first()

        #the structure of any graph should look like this
        #{ 'data': {}, 'height': 0, 'start': dateStat, 'end': datetime.date.today() }
        #with data being an ordered dictionnary of the data to be displayed using keys representing the x axis
        #height being the maximum value of the graph, overflow will happen if it is smaller than anything in data
        #and start and end being the values at the bottom

        indivConsults = { 'data': {}, 'height': 0, 'start': dateStat, 'end': datetime.date.today() }
        cumulConsults = { 'data': {}, 'height': 0, 'start': dateStat, 'end': datetime.date.today() }
        indivFavs = { 'data': {}, 'height': 0, 'start': dateStat, 'end': datetime.date.today() }
        cumulFavs = { 'data': {}, 'height': 0, 'start': dateStat, 'end': datetime.date.today() }

        for i in range(30):
            indivConsults['data'][dateStat] = PostConsult.objects.filter(date=dateStat, post=post).count()

HELBImmo/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <div class="content-section">
        <h1 class="article-metadata">Projet HELBImmo</h1>
        Dans le cadre du cours de Programmation Web II, nous avons été 
        amenés à faire comme projet de fin d’année, un site d’immobilier, 
        créativement dénommé HELBImmo.
        <br><br>
        Ce site a été conçu sur base du 
        <a href="https://www.youtube.com/playlist?list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p">
            django proposé par Corey Schafer sur YouTube.
        </a>
        <img class="d-block mx-auto my-2" src="{% static 'blog/HELB_Logo.png' %}" alt="HELB Logo">
    </div>
{% endblock content %}

HELBImmo/blog/templates/blog/favorites.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <h1 class="mb-3">Vos Favoris</h1>
{% include "blog/subtemplates/pagination.html" %}
{% for fav in favs %}
    {% include "blog/subtemplates/singlepost.html" with post=fav.post %}
{% endfor %}
{% include "blog/subtemplates/pagination.html" %}
{% endblock content %}

HELBImmo/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %}
        <h1 class="text-center mb-4">Bienvenue, {{ user.username }} !</h1>
    {% else %}
        <h1 class="text-center mb-4">Bienvenue !</h1>
    {% endif %}
    {% include "blog/subtemplates/pagination.html" %}
    {% for post in posts %}
        {% include "blog/subtemplates/singlepost.html" with post=post %}
    {% endfor %}
    {% include "blog/subtemplates/pagination.html" %}
{% endblock content %}

HELBImmo/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Supprimez cette annonce ?</legend>
                <h2>Voulez-vous vraiment supprimer cette annonce : "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Oui, supprimez-moi ça</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Non, non, attendez</a>
            </div>
        </form>
    </div>
{% endblock content %}

HELBImmo/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.9.0/css/ol.css">
{% endblock %}
{% block content %}
<article class="content-section">
    <input type="hidden" class="js-view" view-url="{% url 'post-consult' %}" data-postid="{{ view.kwargs.pk }}">
    <div class="article-metadata">
        <h3 class="d-flex justify-content-between mb-2">
            <span>{{ object.type_bien }}</span>
            {% if object.to_sell == True %}
            <span class="text-center">A Vendre</span>
            {% else %}
            <span class="text-center">A Louer</span>
            {% endif %}
        </h3>
    </div>
    <img class="img-fluid w-100 rounded mb-2" src="{{ object.thumbnail.url }}">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' post.author.username %}">
            <img class="text-img rounded-circle mr-1" src="{{ post.author.profile.image.url }}">
            {{ post.author }}
        </a>
        <small class="text-muted">{{ post.date_posted|date:"E d, Y" }}</small>
    </div>
    <div>
        <h3 class="mb-2">
            {{ object.title }}
        </h3>
        <div class="d-flex justify-content-between m-1">
            <span>
                {% include "blog/subtemplates/fav-button.html" %}
            </span>
            <span class="font-weight-bold">{{ object.price }} €</span>
        </div>
        {% if object.author == user %}
            <a class="btn btn-sm btn-info" href="{% url 'post-stats' post.id %}"><i class="bi bi-bar-chart-line"></i> Statistics</a>
            <a class="btn btn-sm btn-secondary" href="{% url 'post-update' object.id %}"><i class="bi bi-arrow-repeat"></i> Update</a>
            <a class="btn btn-sm btn-danger" href="{% url 'post-delete' object.id %}"><i class="bi bi-trash"></i> Delete</a>
        {% endif %}
        <input id="id_type_bien" type="hidden" value="{{ object.type_bien }}">
        <ul class="pl-0 my-2">
            <li id="info_addresse" class="d-block">Addresse : {{ object.road_num }}, {{ object.region_city }} {{ object.country_code }}</li>
            <li id="info_rooms" class="d-flex justify-content-between">Nombres de pièces : <span>{{ object.room_amount }}</span></li>
            <li id="info_surface" class="d-flex justify-content-between">Surface vivable : <span>{{ object.livable_surface }} m²</span></li>
            <li id="info_nb_etage" class="d-flex justify-content-between">Nombre d'étages : <span>{{ object.nb_etage }}</span></li>
            <li id="info_situe_etage" class="d-flex justify-content-between">Sité à l'étage : <span>{{ object.situe_etage }}</span></li>
        </ul>
        Description :
        <p class="article-content rounded border p-1">{{ object.content }}</p>
        <div tabindex="1" id="js-map" data-image="{% static 'blog/marker.png' %}" latitude="{{ object.latitude }}" longitude="{{ object.longitude }}" style="height: 30vh;"></div>
    </div>
</article>
{% if user.is_authenticated and user != object.author %}
    <article class="content-section">
        <form id="question_form" method="post">
            {% csrf_token %}
            <h3 class="article-metadata">Une question ? Posez-là ici : </h3>
            <input id="question_form_data" type="hidden" data-url="{% url 'question-new' %}" data-postid="{{ view.kwargs.pk }}">
            <textarea class="d-block resize-0 w-100 mb-2" style="height:5rem"></textarea>
            <div class="text-right">
                <button class="btn btn-info">Poser une question</button>
            </div>
        </form>
    </article>
{% endif %}
<div id="question_zone">
    {% if questions %}
        {% for question in questions %}
            {% include 'blog/subtemplates/question.html' with question=question %}
        {% endfor %}
    {% else %}
        <div id="noQuestions" class="text-center p-2 text-muted">
            Personne n'a posé de questions...
        </div>
    {% endif %}
</div>
{% endblock content %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.9.0/build/ol.js"></script>
<script src="{% static 'blog/sendConsult.js' %}"></script>
<script src="{% static 'blog/mapDisplay.js' %}"></script>
<script>
    let idField = '#id_type_bien';
    let changeableFields = ['#info_rooms', '#info_nb_etage', '#info_situe_etage']
    let specificFields = {
        'Garage': [],
        'Appartement': ['#info_rooms', '#info_situe_etage'],
        'Maison': ['#info_rooms', '#info_nb_etage']
    }
</script>
<script src="{% static 'blog/fieldHider.js' %}"></script>
<script src="{% static 'blog/FAQscript.js' %}"></script>
{% endblock scripts %}

HELBImmo/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Nouvelle annonce</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Publier</button>
            </div>
        </form>
    </div>
{% endblock content %}
{% block scripts %}
    {{ form.media }}
    <script>
        let idField = '#id_type_bien';
        let changeableFields = ['#div_id_room_amount', '#div_id_nb_etage', '#div_id_situe_etage']
        let specificFields = {
            'Garage': [],
            'Appartement': ['#div_id_room_amount', '#div_id_situe_etage'],
            'Maison': ['#div_id_room_amount', '#div_id_nb_etage']
        }
    </script>
    <script src="{% static 'blog/fieldHider.js' %}"></script>
{% endblock %}

HELBImmo/blog/templates/blog/post_stats.html
{% extends "blog/base.html" %}
{% block content %}
<article class="content-section">
    <div class="article-metadata">
        <h3 class="d-flex justify-content-between mb-2">
            <a class="article-title font-weight-bold" href="{% url 'post-detail' post.id %}">
                <span>{{ post.title }}</span>
            </a>
            <i class="bi bi-bar-chart-line"></i>
        </h3>
    </div>
    <div class="d-flex justify-content-between">
        <div class="flex-grow bg-info text-light text-center line-height-large rounded m-1 py-4">
            Consultations :
            <br>
            {{ consults }}
        </div>
        <div class="flex-grow bg-warning text-light text-center line-height-large rounded m-1 py-4">
            Favoris :
            <br>
            {{ favs }}
        </div>
        <div class="flex-grow bg-danger text-light text-center line-height-large rounded m-1 py-4">
            Questions :
            <br>
            {{ questions }}
        </div>
    </div>
</article>
<article class="content-section">
    <div class="article-metadata">
        <h3 class="mb-2">
            Vues indiviuelles sur les 30 derniers jours
        </h3>
    </div>
    {% include "blog/subtemplates/bar-graph.html" with graph=indivConsults include_key='true' %}
</article>
<article class="content-section">
    <div class="article-metadata">
        <h3 class="mb-2">
            Vues cumulatives sur les 30 derniers jours
        </h3>
    </div>
    {% include "blog/subtemplates/bar-graph.html" with graph=cumulConsults include_key='true' %}
</article>
<article class="content-section">
    <div class="article-metadata">
        <h3 class="mb-2">
            Favoris indiviuels sur les 30 derniers jours
        </h3>
    </div>
    {% include "blog/subtemplates/bar-graph.html" with graph=indivFavs barColor="warning" include_key='true' %}
</article>
<article class="content-section">
    <div class="article-metadata">
        <h3 class="mb-2">
            Favoris cumulatifs sur les 30 derniers jours
        </h3>
    </div>
    {% include "blog/subtemplates/bar-graph.html" with graph=cumulFavs barColor="warning" include_key='true' %}
</article>
{% endblock content %}

HELBImmo/blog/templates/blog/search_results.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<h1>Résultats pour : "{{ terms }}"</h1>
<p class="mb-4">{{ page_obj.paginator.count }} résultat(s)</p>
{% include "blog/subtemplates/pagination.html" with extra_params=url_params %}
{% for post in posts %}
    {% include "blog/subtemplates/singlepost.html" with post=post %}
{% endfor %}
{% include "blog/subtemplates/pagination.html" with extra_params=url_params %}
{% endblock content %}

HELBImmo/blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section media">
        <img class="rounded-circle account-img" src="{{ author.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ author.username }}</h2>
            <p class="text-secondary">{{ author.email }}</p>
            {% if author == user %}
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'profile' %}">Mettre à jour</a>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'criteria' %}">Changer les critères</a>
            {% endif %}
        </div>
    </div>
    <h3 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h3>
    {% include "blog/subtemplates/pagination.html" %}
    {% for post in posts %}
        {% include "blog/subtemplates/singlepost.html" with post=post %}
    {% endfor %}
    {% include "blog/subtemplates/pagination.html" %}
{% endblock content %}